language: python
python:
  - "3.6"

# command to install dependencies
install:
  - "pip install -r requirements.txt"
# command to run tests
cache: false
before_script:
  - sudo -u postgres bash -c "psql -c \"CREATE USER mwas WITH PASSWORD '';\""
  - psql -c 'create database bucketlist_db;' -U postgres
  - psql -c 'create database test_db;' -U postgres
  - "rm -rf migrations/"
  - " python run.py db init"
  - " python run.py db migrate"
  - " python run.py db upgrade"

script: "nosetests"

services:
  - postgresql

 #Coveralls
after_success:
  - coveralls